export const pokemonEmojis = {
  bug: "🐞",
  electric: "⚡️",
  dragon: "🐲",
  flying: "🦋",
  poison: "☠️",
  ground: "🏔️",
  fire: "🔥",
  dark: "⚫",
  grass: "🌿",
  rock: "🗿",
  normal: "🐻",
  water: "💧",
  fighting: "⚔️",
  ice: "❄️",
  fairy: "🧚",
  ghost: "👻",
  steel: "⚙️",
  psychic: "👁️",
};
